/* config.h.  Generated by cmake from config.h.cmake  */

#define LIBOPING_VERSION "${PROJECT_VERSION}"
#cmakedefine LIBOPING_GIT_REVISION "${LIBOPING_GIT_REVISION}"
#cmakedefine LIBOPING_BUILD_TIMESTAMP "${LIBOPING_BUILD_TIMESTAMP}"